# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param synth.incrementalSynthesisCache C:/Users/wilsonic/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-23764-RHIT-R90VM7XZ/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.cache/wt} [current_project]
set_property parent.project_path {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/imports/Term Project SourceFiles Folder/CRTClock2022Template.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/imports/Term Project SourceFiles Folder/CRTcontroller2022fall.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/imports/Term Project SourceFiles Folder/FallingEdgePositiveOneShot.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/imports/Term Project SourceFiles Folder/Game2022fallTemplate.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/new/PositiveClockedOneShot.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/imports/Term Project SourceFiles Folder/UniversalCounter2022fall.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/imports/vga_sources2022/VGA7SegDisplay_Karl_Reese_fall2019.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/imports/Term Project SourceFiles Folder/hsyncModule2022fall.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/new/scoreCounter.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/imports/Term Project SourceFiles Folder/vsyncModule2022fallTemplate.v}
  {C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/sources_1/imports/Term Project SourceFiles Folder/PongGame2022fallTemplate.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/constrs_1/imports/new/pongPhase2_LJB_ICW.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/wilsonic/Documents/classes 2022/fall 2022/ece433/ece433-final-project/VerilogPongGame/PongGamefall2022Phase4_LJB_ICW/PongGamefall2022Phase4_LJB_ICW.srcs/constrs_1/imports/new/pongPhase2_LJB_ICW.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top PongGame2022fallTemplate -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PongGame2022fallTemplate.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PongGame2022fallTemplate_utilization_synth.rpt -pb PongGame2022fallTemplate_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
