# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SeniorFallQuarter/AdvVerilog/Projects/PongGame2022fallTemplate/PongGame2022fallTemplate.srcs/sources_1/ip/clk50Mhz/clk50Mhz.xci
# IP: The module: 'clk50Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SeniorFallQuarter/AdvVerilog/Projects/PongGame2022fallTemplate/PongGame2022fallTemplate.srcs/sources_1/ip/clk50Mhz/clk50Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50Mhz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/SeniorFallQuarter/AdvVerilog/Projects/PongGame2022fallTemplate/PongGame2022fallTemplate.srcs/sources_1/ip/clk50Mhz/clk50Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/SeniorFallQuarter/AdvVerilog/Projects/PongGame2022fallTemplate/PongGame2022fallTemplate.srcs/sources_1/ip/clk50Mhz/clk50Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/SeniorFallQuarter/AdvVerilog/Projects/PongGame2022fallTemplate/PongGame2022fallTemplate.srcs/sources_1/ip/clk50Mhz/clk50Mhz.xci
# IP: The module: 'clk50Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SeniorFallQuarter/AdvVerilog/Projects/PongGame2022fallTemplate/PongGame2022fallTemplate.srcs/sources_1/ip/clk50Mhz/clk50Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/SeniorFallQuarter/AdvVerilog/Projects/PongGame2022fallTemplate/PongGame2022fallTemplate.srcs/sources_1/ip/clk50Mhz/clk50Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/SeniorFallQuarter/AdvVerilog/Projects/PongGame2022fallTemplate/PongGame2022fallTemplate.srcs/sources_1/ip/clk50Mhz/clk50Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
